name: Process Video

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  process_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg python3 python3-pip
          pip install -r requirements.txt || echo "requirements.txt not found, skipping."

      - name: Download Input Video
        run: |
          wget -O "Doraemon_S20E02.mkv" "http://gfs204n110.userstorage.mega.co.nz/dl/fn9YrF9T-hMa7gKQoJUc3r1HBLM7KmLmP3rCS6iFU2BeAI5kOgIBGiKtka1gnrzWoV1NjB4oNOGQXJ8fK805zNh6VTZuHBISJmDIPZjs1KaJ-MuJRTuYabDhJblHVh6JfYovQZLdZ4YmW1woXiGzjzSX18T2LC7L-eJdF-VynOOE_yyTRpTOtvPaVpS6jxn2l-enRqcHCaWWuRHIkCq7Pk5tPXo0l53MwlWuTaqepzMA3X-UZTNILSIQsw"

      - name: Verify Downloaded Video
        run: |
          if [ ! -s "Doraemon_S20E02.mkv" ]; then
            echo "ERROR: Downloaded file is empty!"
            exit 1
          fi

      - name: Convert Video Format (if needed)
        run: ffmpeg -i Doraemon_S20E02.mkv -c:v copy -c:a copy input.mp4

      - name: Run Sketch Effect Script
        run: |
          if [ -f "sketch_effect.py" ]; then
            python3 sketch_effect.py --input input.mp4 --output output.mp4
          else
            echo "sketch_effect.py not found!"
            exit 1
          fi

      - name: Check Output File
        run: |
          if [ ! -s "output.mp4" ]; then
            echo "ERROR: Output video is missing!"
            exit 1
          fi

      - name: Upload Processed Video to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processed-video
          path: output.mp4
