name: Process Video

on:  
  push:  
    branches: [ main ]  
  workflow_dispatch:  

jobs:  
  process_video:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v4  

      - name: Install Dependencies  
        run: |  
          sudo apt update  
          sudo apt install -y ffmpeg wget  

      - name: Download Input Video  
        run: |  
          wget -O "[Toonworld4all] Doraemon (2005) S21E18 720p x264 Multi Audio [Uncut]" "https://aws.flapdoodle.cyou/download/MW9TRXBlOG5nRi1MbDd4TWYxSm1iY3BVRElYUFlXd3dIQDE3NDMzMjczOTgxNDZAMjQwOTo0MDQyOjhlOTE6ZTA4ODo2OTYwOjIxZjE6YzU5YjphMDM5QE9zeUhMYmltd3RVMHFqMnA5VXRoT3BJVjRGNmdNV2NDb2IzQjlxMHhLUG89/[Toonworld4all]%20Doraemon%20(2005)%20S21E18%20720p%20x264%20Multi%20Audio%20[Uncut].mkv"  

      - name: Verify Downloaded Video  
        run: |  
          if [ ! -s [Toonworld4all] Doraemon (2005) S21E18 720p x264 Multi Audio [Uncut].mkv ]; then  
            echo "ERROR: Input video is missing or empty!"  
            exit 1  
          fi  
          file [Toonworld4all] Doraemon (2005) S21E18 720p x264 Multi Audio [Uncut].mkv  

      - name: Convert Video Format (if needed)  
        run: |  
          ffmpeg -i [Toonworld4all] Doraemon (2005) S21E18 720p x264 Multi Audio [Uncut] -c:v libx264 -preset fast -crf 23 -c:a aac -b:a 128k output.mp4  

      - name: Run Sketch Effect Script  
        run: |  
          python sketch.py output.mp4 processed.mp4  

      - name: Check Output File  
        run: |  
          if [ ! -s processed.mp4 ]; then  
            echo "ERROR: Processed video is missing or empty!"  
            exit 1  
          fi  

      - name: Upload Processed Video to GitHub Artifacts  
        uses: actions/upload-artifact@v4  
        with:  
          name: processed-video  
          path: processed.mp4
